name: iOS构建

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

# 添加权限以允许创建Release
permissions:
  contents: write

jobs:
  build:
    name: 构建与打包IPA
    runs-on: macos-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Xcode版本
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: 设置Ruby和CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: 安装依赖
      run: |
        gem install cocoapods
        if [ -f "Podfile" ]; then
          pod install --repo-update
        else
          echo "没有找到Podfile，跳过CocoaPods依赖安装"
        fi
      working-directory: ${{ github.workspace }}
      
    - name: 修复Info.plist重复问题
      run: |
        # 创建桥接头文件
        echo "int poc(char *path);" > iDevice_ZH/iDevice_ZH-Bridge-Header.h
        
        # 修复桥接头文件路径
        sed -i '' 's|/Users/geosn0w/Desktop/iDevice_ZH/iDevice_ZH/iDevice_ZH-Bridge-Header.h|iDevice_ZH/iDevice_ZH-Bridge-Header.h|g' iDevice_ZH.xcodeproj/project.pbxproj
        
        # 查找并移除项目中可能导致Info.plist重复的问题
        if grep -q "Info.plist in Resources" iDevice_ZH.xcodeproj/project.pbxproj; then
          echo "在Copy Bundle Resources阶段找到Info.plist引用，准备移除..."
          sed -i '' '/Info.plist in Resources/d' iDevice_ZH.xcodeproj/project.pbxproj
        fi
        
        # 确保项目正确使用Info.plist
        if [ -f "iDevice_ZH/Info.plist" ]; then
          echo "已找到Info.plist文件"
        else
          echo "警告: 未找到Info.plist文件，请检查项目结构"
        fi
    
    - name: 创建导出选项Plist
      run: |
        cat > exportOptions.plist << EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
        </dict>
        </plist>
        EOL
    
    - name: 构建和归档应用
      run: |
        # 确定工作区或项目参数
        if [ -f "iDevice_ZH.xcworkspace/contents.xcworkspacedata" ]; then
          WORKSPACE_ARG="-workspace iDevice_ZH.xcworkspace"
        else
          WORKSPACE_ARG="-project iDevice_ZH.xcodeproj"
        fi
        
        # 列出可用的scheme
        xcodebuild -list $WORKSPACE_ARG
        
        # 构建并归档应用
        xcodebuild clean archive $WORKSPACE_ARG \
          -scheme "iDevice_ZH" \
          -configuration Debug \
          -archivePath $RUNNER_TEMP/iDevice_ZH.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          SWIFT_OPTIMIZATION_LEVEL="-Onone" \
          IPHONEOS_DEPLOYMENT_TARGET=12.0
      
    - name: 打包IPA
      run: |
        # 创建IPA结构
        mkdir -p $RUNNER_TEMP/build/Payload
        
        # 查找应用程序位置
        APP_PATH="$RUNNER_TEMP/iDevice_ZH.xcarchive/Products/Applications/iDevice_ZH.app"
        if [ -d "$APP_PATH" ]; then
          echo "找到应用程序: $APP_PATH"
          cp -r "$APP_PATH" $RUNNER_TEMP/build/Payload/
        else
          echo "警告: 未找到预期的应用路径，尝试查找其他可能的位置..."
          FOUND_APP=$(find $RUNNER_TEMP -name "*.app" -type d | head -n 1)
          if [ -n "$FOUND_APP" ]; then
            echo "找到替代应用路径: $FOUND_APP"
            cp -r "$FOUND_APP" $RUNNER_TEMP/build/Payload/
          else
            echo "错误: 未找到任何应用文件"
            exit 1
          fi
        fi
        
        # 打包IPA
        cd $RUNNER_TEMP/build
        zip -r iDevice_ZH.ipa Payload
        
        # 显示ZIP内容验证
        echo "IPA文件内容:"
        unzip -l iDevice_ZH.ipa | head -n 20
    
    - name: 上传IPA作为工作流产物
      uses: actions/upload-artifact@v4
      with:
        name: iDevice_ZH-unsigned
        path: ${{ runner.temp }}/build/iDevice_ZH.ipa
    
    - name: 获取当前日期
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
    
    - name: 创建Release
      if: github.event_name != 'pull_request'
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ steps.date.outputs.date }}
        name: 自动构建 ${{ steps.date.outputs.date }}
        body: |
          iDevice_ZH自动构建版本
          
          构建时间: ${{ steps.date.outputs.date }}
          未签名IPA文件，需要自行签名后安装。
        draft: false
        prerelease: true
        files: ${{ runner.temp }}/build/iDevice_ZH.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  syntax_check:
    name: Swift语法检查
    runs-on: macos-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 环境信息
        run: |
          swift --version
          echo "代码库结构:"
          find . -name "*.swift" | wc -l
          echo "找到的Swift文件数量."
      
      - name: Swift语法检查
        run: |
          # 简单语法检查
          find iDevice_ZH -name "*.swift" -print0 | xargs -0 -n1 swift -syntax-only || true
          
          # 返回成功状态
          echo "基本语法检查完成。"
          exit 0