    - name: 手动创建IPA
      run: |
        # 手动打包IPA
        mkdir -p $RUNNER_TEMP/ipa/Payload
        
        # 查找应用程序位置
        echo "查找应用程序..."
        APP_PATH="$RUNNER_TEMP/iDevice_ZH.xcarchive/Products/Applications/iDevice_ZH.app"
        
        # 如果找不到主路径，搜索整个归档目录
        if [ ! -d "$APP_PATH" ]; then
          echo "在主路径未找到应用，搜索其他位置..."
          APP_PATH=$(find $RUNNER_TEMP/iDevice_ZH.xcarchive -name "*.app" -type d | head -n 1)
        fi
        
        # 如果仍找不到，尝试在build目录查找
        if [ ! -d "$APP_PATH" ]; then
          echo "在归档中未找到应用，搜索构建目录..."
          APP_PATH=$(find $GITHUB_WORKSPACE/build -name "*.app" -type d | head -n 1)
        fi
        
        # 如果找到应用，进行打包
        if [ -d "$APP_PATH" ]; then
          echo "找到应用程序: $APP_PATH，开始打包IPA..."
          
          # 获取应用程序名称（用于命名IPA文件）
          APP_NAME=$(basename "$APP_PATH" .app)
          echo "应用程序名称: $APP_NAME"
          
          # 验证应用包内的Info.plist
          if [ -f "$APP_PATH/Info.plist" ]; then
            echo "应用包中已有Info.plist文件"
            plutil -p "$APP_PATH/Info.plist" || echo "Info.plist可能存在问题"
            # 从Info.plist获取Bundle ID
            BUNDLE_ID=$(defaults read "$APP_PATH/Info.plist" CFBundleIdentifier)
            echo "Bundle ID: $BUNDLE_ID"
          else
            echo "警告：应用包中没有找到Info.plist，尝试复制..."
            cp iDevice_ZH/Info.plist "$APP_PATH/Info.plist"
          fi
          
          # 复制应用到Payload目录
          cp -R "$APP_PATH" $RUNNER_TEMP/ipa/Payload/
          
          # 打包IPA - 确保命名与应用一致
          cd $RUNNER_TEMP/ipa
          IPA_NAME="${APP_NAME}.ipa"
          zip -r "$IPA_NAME" Payload
          
          # 确保IPA确实存在
          if [ -f "$IPA_NAME" ]; then
            echo "成功创建IPA: $IPA_NAME ($(du -h "$IPA_NAME" | cut -f1))"
            # 创建一个统一名称的副本，以便上传步骤总是使用一致的文件名
            cp "$IPA_NAME" "iDevice_ZH.ipa"
            ls -la
          else
            echo "错误: IPA文件 $IPA_NAME 未能创建"
            ls -la
            exit 1
          fi
        else
          echo "错误: 无法找到应用程序"
          exit 1
        fi
    
    - name: 上传IPA文件
      uses: actions/upload-artifact@v4
      with:
        name: iDevice_ZH-IPA
        path: ${{ runner.temp }}/ipa/*.ipa
        
    - name: 上传归档文件
      uses: actions/upload-artifact@v4
      with:
        name: iDevice_ZH-Archive
        path: ${{ runner.temp }}/iDevice_ZH.xcarchive/